# Generated by Django 5.1 on 2025-09-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('loction', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Upcoming', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.usertable')),
            ],
        ),
    ]
