# Generated by Django 5.1 on 2025-09-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='title',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
