# Generated by Django 5.1 on 2025-09-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_admintable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admintable',
            old_name='id',
            new_name='admin_id',
        ),
    ]
